Feature/pattern scaffolding scss
mediacurrent/theme_generator_8 pull request #115
Opened 2021-06-28 18:58 UTC by Tregonia

2021-06-28 19:00 UTC, Tregonia commented
https://github.com/mediacurrent/theme_generator_8/issues/114

2021-06-28 21:30 UTC, mariohernandez requested changes
Although there might be some useful things in this PR, I don't feel we need to maintain code that is part of Pattern Lab.  Pattern Lab is constantly changing and don't think linting its code or doing other code updates is the best use of our time.  Let's discuss with the team to determine what makes sense to keep from this PR.

2021-06-28 22:02 UTC, Tregonia commented
I do not understand what you are referring to with the linting. There is 1 scss file at the location that the gulp tasks. This can be expended on, but there is only 1. The contents of this css file are for style deviations we add to our styleguides. For example, the reason our icon component looks the way it does, is because the styles in this file. 

> Although there might be some useful things in this PR, I don't feel we need to maintain code that is part of Pattern Lab. Pattern Lab is constantly changing and don't think linting its code or doing other code updates is the best use of our time. Let's discuss with the team to determine what makes sense to keep from this PR.

2021-06-28 22:11 UTC, rlahoda approved these changes
I think adding this in makes a lot more sense than other possible options for overriding styles in the patternlab display. In another project, we're adding in CSS overrides in the `_head.twig` file in a `<style>` tag so adding this into the compiled styles seems like a good idea to consolidate and better track the styles.

I'm approving this with a couple very minor tweaks that aren't required but would be helpful.

2021-06-28 22:11 UTC, rlahoda commented on generators/app/templates/_gulp-tasks/compress.js
> +      './src/patterns/{global,layout,components}/**/*{.gif,.png,.jpg,.svg}'
This is fine, can you add .jpeg files as well? that was an update I had planned on making after running into that issue previously.

2021-06-28 22:11 UTC, rlahoda commented on generators/app/templates/_gulpfile.js
> +    './src/patterns/**/**/*{.gif,.jpg,.png,.svg}',
Same as my comment above about adding .jpeg

2021-06-28 22:13 UTC, rlahoda commented
Also, I changed the base for the PR to develop instead of `main`. To better track what's getting added to NPM, it makes sense to only merge into `main` when the code is getting release on NPM as well.

2021-07-01 23:11 UTC, mariohernandez approved these changes

2021-07-01 23:11 UTC, merged

2021-07-01 23:15 UTC, Tregonia commented on generators/app/templates/_gulp-tasks/compress.js
> +      './src/patterns/{global,layout,components}/**/*{.gif,.png,.jpg,.svg}'
We can add that. I wonder tho, that is 5 items at this point. Is there a better way to represent this; aside from more commas?